services:
  mysql:
    image: mysql:8
    container_name: prestashop-db
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_ROOT_PASSWORD: prestashop
    ports:
      - 3306:3306
    networks:
      - prestashop_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: prestashop
    ports:
      - 8081:80
    depends_on:
      - mysql
    networks:
      - prestashop_network

  prestashop:
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    image: patrykswietlik/project-prestashop:latest
    container_name: prestashop
    ports:
      - 18977:443
    depends_on:
      - mysql
    environment:
      DB_SERVER: prestashop-db
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: prestashop
    networks:
      - prestashop_network

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - '11211:11211'
    networks:
      - prestashop_network

  selenium-tests:
    build:
      context: .
      dockerfile: project-prestashop/tests/Dockerfile
    depends_on:
      - prestashop
    networks:
      - prestashop_network
    healthcheck:
      test: ["CMD", "curl", "--silent", "https://prestashop:18977", "||", "exit", "1"]
      interval: 30s
      retries: 5
      start_period: 10s
    environment:
      SHOP_URL: "https://prestashop:18977"


networks:
  prestashop_network:
