name: buid and publish docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Logowanie do Docker Hub
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}  # Zmienna środowiskowa przechowująca dane logowania
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        context: .
        file: ./config/Dockerfile
        tags: patrykswietlik/project-prestashop:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      prestashop:
        image: patrykswietlik/project-prestashop:latest
        ports:
          - 443:443
        options: --health-cmd="curl --silent --fail http://localhost/ > /dev/null || exit 1" --health-interval=30s --health-retries=5 --health-timeout=10s

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and run test container
        run: |
          docker build -f project-prestashop/tests/Dockerfile -t selenium-tests .
          docker run --network="host" selenium-tests
