name: buid and publish docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Logowanie do Docker Hub
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}  # Zmienna środowiskowa przechowująca dane logowania
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        context: .
        file: ./config/Dockerfile
        tags: patrykswietlik/project-prestashop:latest
        build-args: |
          COOKIE_KEY=${{ secrets.COOKIE_KEY }}
          COOKIE_IV=${{ secrets.COOKIE_IV }}
          NEW_COOKIE_KEY=${{ secrets.NEW_COOKIE_KEY }}
